name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@d27d2d3b49bcf14db85bdfb0f57956abf18bb091 # pinned to latest
    secrets: inherit
