name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@38cd6ebc01e8b5b14ac9a90a5579d04b02e79099 # pinned to latest
    secrets: inherit
