name: Module Test Harness

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@38cd6ebc01e8b5b14ac9a90a5579d04b02e79099
    with:
      provider: digitalocean
      working_directory: ./_examples/basic/

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@38cd6ebc01e8b5b14ac9a90a5579d04b02e79099
    with:
      provider: digitalocean
      working_directory: ./_examples/complete/
