name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@d27d2d3b49bcf14db85bdfb0f57956abf18bb091 # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
